### PR TITLE
WIP: Test vectors JSON

### PR DESCRIPTION
**Pull request by ErinHales**
- Created `testVectors.json`
- Added variables from BTCUtils.js and ValidateSPV.js
- Created utils function that iterates through all of the json data and deserializes all hex values
- Replaced old values with values from `testVectors.json`

To do:
 - [x] Update `utils.test.js`
 - [x] Update solidity tests
 - [x] Clean up code

### CODE REVIEW

**Comment by prestwich** [comment]
Okay. Progress is looking good. I've been able to run the tests locally

**Comment by prestwich** [comment]
Don't forget to lint as you go. Several `let`s should be `const`s

**Comment by prestwich** [comment]
There are a few things in the `testVectors.json` that should be big ints. they'll need to be hex encoded

you can remove `acummulated_difficulty` keys from all objects in `RETARGET_TUPLES`

**Comment by prestwich** [comment]
opened #33 for you :+1:

**Comment by ErinHales** [comment]
Did you remove the `accumulated_difficulty` keys already?  Or did you mean `difficulty` or `accumulated_work`?

**Comment by prestwich** [comment]
> Did you remove the `accumulated_difficulty` keys already? Or did you mean `difficulty` or `accumulated_work`?

I meant `accumulated_work` and it is removed in #33

**Comment by prestwich** [comment]
On second thought, updating the solidity can be a separate PR

**Pull request merged**
