### PR TITLE
Adds some additional docs fixes

### PR DESCRIPTION
**Pull request by sr-gi**
May add some more if I find any, leaving it as a draft for now.

### CODE REVIEW

**Comment by prestwich** [comment]
Will more commits be added to this, or is it ready for merging?

**Comment by sr-gi** [comment]
I'd wait since I'm still checking some of the files, and I may add some more if I find any. Will move from draft to PR once ready.

**Comment by sr-gi** [comment]
As a side note, `validateVin` and `validateVout` are placed under Witness TX, but they work for both legacy and segwit.

**Comment by prestwich** [comment]
Really the distinction between Legacy and Witness is no longer useful, and should probably be removed

**Pull request merged**
